name: Build and Upload CRX [OLD]

on:
  workflow_dispatch:

jobs:
  build_crx:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 获取短提交哈希
    - name: Get Short Commit Hash
      id: vars
      run: |
        SHORT_COMMIT=$(git rev-parse --short=6 HEAD)
        echo "SHORT_COMMIT=$SHORT_COMMIT" >> $GITHUB_ENV

    # 使用私钥生成 CRX 文件
    - name: Build CRX file
      env:
        PEM_SECRET: ${{ secrets.PEM_SECRET }}
      run: |
        openssl base64 -d -out private.pem <<< "$PEM_SECRET"
        REPO_NAME="NoUTM" # 手动设置仓库名，避免获取错误
        OUTPUT_FILE="${REPO_NAME}_${SHORT_COMMIT}.crx"
        cd src
        zip -r "$OUTPUT_FILE" ./* # 仅打包 src 目录的内容
        mv "$OUTPUT_FILE" ../ # 将生成的 CRX 文件移回根目录
        cd ..

    # 合并 /utilities 中的文件与生成的 CRX 文件
    - name: Merge utilities and CRX
      run: |
        mkdir -p publish
        cp "NoUTM_${SHORT_COMMIT}.crx" publish/
        if [ -d "utilities" ]; then
          cp -r utilities/* publish/
        fi

    # 上传工件并动态命名
    - name: Upload publish folder
      uses: actions/upload-artifact@v4
      with:
        name: NoUTM_${{ env.SHORT_COMMIT }}
        path: publish/
